// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnpzXYCZDwRG5Wwz5A93hVqXZ0sLt6rx4',
    appId: '1:540039956772:android:eb0adb28ba5040bb500bb1',
    messagingSenderId: '540039956772',
    projectId: 'tamrini-app',
    databaseURL: 'https://tamrini-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tamrini-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbp0oAJoXzputASM3X5tdtPekpua20D48',
    appId: '1:540039956772:ios:8da67bc4b72c455f500bb1',
    messagingSenderId: '540039956772',
    projectId: 'tamrini-app',
    databaseURL: 'https://tamrini-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tamrini-app.appspot.com',
    androidClientId: '540039956772-98kgj9s3pnrvdn92ia3ren42nd7k949v.apps.googleusercontent.com',
    iosClientId: '540039956772-i52ufmel7nko6k1ag829vkocu8sdodb3.apps.googleusercontent.com',
    iosBundleId: 'com.tamrini.app',
  );
}
